# Generated by Django 5.2.8 on 2025-11-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('obs_time_utc', models.DateTimeField()),
                ('obs_time_local', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=100)),
                ('software_type', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=10)),
                ('solar_radiation', models.FloatField()),
                ('longitude', models.FloatField()),
                ('realtime_frequency', models.IntegerField(blank=True, null=True)),
                ('epoch', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('uv', models.FloatField()),
                ('wind_direction', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('qc_status', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('heat_index', models.IntegerField()),
                ('dewpoint', models.IntegerField()),
                ('wind_chill', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('wind_gust', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('precip_rate', models.FloatField()),
                ('precip_total', models.FloatField()),
                ('elevation', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Observation',
                'verbose_name_plural': 'Weather Observations',
                'ordering': ['-obs_time_utc'],
            },
        ),
    ]
