# Generated by Django 4.2.26 on 2025-11-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_time_utc', models.DateTimeField()),
                ('obs_time_local', models.DateTimeField()),
                ('epoch', models.BigIntegerField()),
                ('solar_radiation_high', models.IntegerField(blank=True, null=True)),
                ('uv_high', models.IntegerField(blank=True, null=True)),
                ('winddir_avg', models.IntegerField(blank=True, null=True)),
                ('humidity_high', models.IntegerField(blank=True, null=True)),
                ('humidity_low', models.IntegerField(blank=True, null=True)),
                ('humidity_avg', models.IntegerField(blank=True, null=True)),
                ('temp_high', models.FloatField(blank=True, null=True)),
                ('temp_low', models.FloatField(blank=True, null=True)),
                ('temp_avg', models.FloatField(blank=True, null=True)),
                ('windspeed_high', models.FloatField(blank=True, null=True)),
                ('windspeed_low', models.FloatField(blank=True, null=True)),
                ('windspeed_avg', models.FloatField(blank=True, null=True)),
                ('windgust_high', models.FloatField(blank=True, null=True)),
                ('windgust_low', models.FloatField(blank=True, null=True)),
                ('windgust_avg', models.FloatField(blank=True, null=True)),
                ('dewpt_high', models.FloatField(blank=True, null=True)),
                ('dewpt_low', models.FloatField(blank=True, null=True)),
                ('dewpt_avg', models.FloatField(blank=True, null=True)),
                ('windchill_high', models.FloatField(blank=True, null=True)),
                ('windchill_low', models.FloatField(blank=True, null=True)),
                ('windchill_avg', models.FloatField(blank=True, null=True)),
                ('heatindex_high', models.FloatField(blank=True, null=True)),
                ('heatindex_low', models.FloatField(blank=True, null=True)),
                ('heatindex_avg', models.FloatField(blank=True, null=True)),
                ('pressure_max', models.FloatField(blank=True, null=True)),
                ('pressure_min', models.FloatField(blank=True, null=True)),
                ('pressure_trend', models.FloatField(blank=True, null=True)),
                ('precip_rate', models.FloatField(blank=True, null=True)),
                ('precip_total', models.FloatField(blank=True, null=True)),
                ('qc_status', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Observation Météo',
                'verbose_name_plural': 'Observations Météo',
                'ordering': ['-obs_time_utc'],
            },
        ),
        migrations.CreateModel(
            name='StationMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(max_length=50)),
                ('nom', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Station Météo',
                'verbose_name_plural': 'Stations Météo',
            },
        ),
        migrations.DeleteModel(
            name='WeatherObservation',
        ),
        migrations.AddField(
            model_name='observationmeteo',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='weather.stationmeteo'),
        ),
        migrations.AlterUniqueTogether(
            name='observationmeteo',
            unique_together={('station', 'epoch')},
        ),
    ]
